[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vlsi"
version = "0.0.1"
description = "variable length spatial index - encode arbitary length bytes in nifti + data sidecar file"
authors = [
    {name = "INM1-BDA", email = "inm1-bda@fz-juelich.de"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]
dependencies = [
    "nibabel",
]

[project.optional-dependencies]
dev = ["pytest", "flake8", "pylint", "requests", "Flake8-pyproject"]

[project.urls]
Homepage = "https://github.com/fzj-inm1-bda/vlsi"

[tool.setuptools]
packages = ["vlsi"]

[tool.black]
line-length = 88
target-version = ["py39"]


[tool.flake8]
per-file-ignores = [
    "__init__.py:F401,E402",
]
# Ignoring:
# E501: line too long
# W503: Line break occurred before a binary operator https://www.flake8rules.com/rules/W503.html
# n.b. PEP now recommends linebreak BEFORE operator. see https://peps.python.org/pep-0008/#should-a-line-break-before-or-after-a-binary-operator
# E731: do not assign a lambda expression, use a def
# E203: Whitespace before ':' (E203). (E203 is not PEP 8 compliant and auto formatter will break it)

ignore = [
    "E203", # Whitespace before ':' (handled by Black)
    "E501", # Line too long (handled by Black)
    "W503", # Line break before binary operator (handled by Black)
    "E731", # Unused import
]
exclude = [
    "venv",
    ".git",
    "__pycache__"
]
