name: "[tests]"
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install deps"
        run: |
          pip install .[dev]
      - name: "Run lint"
        run: flake8 vlsi

  unittests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install deps"
        run: |
          pip install .[dev]
      - name: "Run unit_tests"
        run: pytest unit_tests/

  e2e_read:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install deps"
        run: |
          pip install .[dev]
      - name: "Run e2e tests"
        run: pytest e2e/test_reading*

  # e2e writeread is intensive task (~2h to complete)
  # only run if push to main
  e2e_writeread:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install deps"
        run: |
          pip install .[dev]
      - name: "Run e2e tests"
        run: pytest e2e/test_writing_reading.py
